#include <jit/insns/binary.h>
#include <jit/insns/unary.h>
#include <jit/insns/compare.h>
#include <jit/insns/transfer.h>
#include <jit/insns/network.h>
#include <jit/insns/load.h>
#include <jit/insns/store.h>
#include <jit/insns/argument.h>
#include <jit/insns/branch.h>
#include <jit/insns/jump.h>
#include <jit/insns/function.h>
#include <jit/insns/labels.h>
#include <jit/insns/pseudo.h>
