  errtab[22] ("expected numeric constant after unary identity operator", 41);
  errtab[23] ("expected numeric constant after unary negative operator", 41);
  errtab[24] ("expected numeric constant after unary bitwise complement operator", 41);
  errtab[25] ("compile-time function call cannot occur in constant expression", 273);
  errtab[25] ("expected numeric constant before binary bitwise AND operator", 38);
  errtab[25] ("expected numeric constant before binary bitwise OR operator", 124);
  errtab[25] ("expected numeric constant before binary bitwise XOR operator", 94);
  errtab[25] ("expected numeric constant before binary division operator", 47);
  errtab[25] ("expected numeric constant before binary left shift operator", 280);
  errtab[25] ("expected numeric constant before binary modulo division operator", 37);
  errtab[25] ("expected numeric constant before binary multiplication operator", 42);
  errtab[25] ("expected numeric constant before binary power operator", 279);
  errtab[25] ("expected numeric constant before binary right shift operator", 281);
  errtab[25] ("floating point variable cannot occur in constant expression", 272);
  errtab[25] ("function reference cannot occur in constant expression", 274);
  errtab[25] ("instruction reference cannot occur in constant expression", 270);
  errtab[25] ("integer variable cannot occur in constant expression", 271);
  errtab[25] ("no newline at end of file", 41);
  errtab[57] ("expected operator before numeric constant", 262);
  errtab[58] ("cannot apply binary bitwise AND operator to floating point constants", 38);
  errtab[58] ("cannot apply binary bitwise OR operator to floating point constants", 124);
  errtab[58] ("cannot apply binary bitwise XOR operator to floating point constants", 94);
  errtab[58] ("cannot apply binary left shift operator to floating point constants", 280);
  errtab[58] ("cannot apply binary right shift operator to floating point constants", 281);
  errtab[58] ("expected operator before numeric constant", 261);
  errtab[61] ("cannot assign to a register directly, use one of the mov instructions", 263);
  errtab[61] ("cannot assign to a register directly, use one of the mov instructions", 264);
  errtab[61] ("cannot assign to a register directly, use one of the mov instructions", 265);
  errtab[61] ("cannot assign to a register directly, use one of the mov instructions", 266);
  errtab[61] ("cannot assign to a register directly, use one of the mov instructions", 267);
  errtab[61] ("cannot assign to a register directly, use one of the mov instructions", 268);
  errtab[61] ("lvalue required as receiving operand of assignment", 261);
  errtab[61] ("lvalue required as receiving operand of assignment", 262);
  errtab[61] ("lvalue required as receiving operand of assignment", 273);
  errtab[61] ("lvalue required as receiving operand of assignment", 274);
  errtab[61] ("operators are invalid as receiving operand of assignments", 124);
  errtab[61] ("operators are invalid as receiving operand of assignments", 279);
  errtab[61] ("operators are invalid as receiving operand of assignments", 280);
  errtab[61] ("operators are invalid as receiving operand of assignments", 281);
  errtab[61] ("operators are invalid as receiving operand of assignments", 37);
  errtab[61] ("operators are invalid as receiving operand of assignments", 38);
  errtab[61] ("operators are invalid as receiving operand of assignments", 42);
  errtab[61] ("operators are invalid as receiving operand of assignments", 43);
  errtab[61] ("operators are invalid as receiving operand of assignments", 45);
  errtab[61] ("operators are invalid as receiving operand of assignments", 47);
  errtab[61] ("operators are invalid as receiving operand of assignments", 94);
  errtab[63] ("cannot mix floating point and integral in operands to binary bitwise OR operator", 262);
  errtab[63] ("compile-time function call cannot occur in constant expression", 273);
  errtab[63] ("expected integral constant before ')' token", 41);
  errtab[63] ("floating point variable cannot occur in constant expression", 272);
  errtab[63] ("function reference cannot occur in constant expression", 274);
  errtab[63] ("instruction reference cannot occur in constant expression", 270);
  errtab[63] ("integer variable cannot occur in constant expression", 271);
  errtab[64] ("cannot mix floating point and integral in operands to binary bitwise XOR operator", 262);
  errtab[64] ("compile-time function call cannot occur in constant expression", 273);
  errtab[64] ("expected integral constant before ')' token", 41);
  errtab[64] ("floating point variable cannot occur in constant expression", 272);
  errtab[64] ("function reference cannot occur in constant expression", 274);
  errtab[64] ("instruction reference cannot occur in constant expression", 270);
  errtab[64] ("integer variable cannot occur in constant expression", 271);
  errtab[65] ("cannot mix floating point and integral in operands to binary bitwise AND operator", 262);
  errtab[65] ("compile-time function call cannot occur in constant expression", 273);
  errtab[65] ("expected integral constant before ')' token", 41);
  errtab[65] ("floating point variable cannot occur in constant expression", 272);
  errtab[65] ("function reference cannot occur in constant expression", 274);
  errtab[65] ("instruction reference cannot occur in constant expression", 270);
  errtab[65] ("integer variable cannot occur in constant expression", 271);
  errtab[66] ("cannot mix floating point and integral in operands to binary left shift operator", 262);
  errtab[66] ("compile-time function call cannot occur in constant expression", 273);
  errtab[66] ("expected integral constant before ')' token", 41);
  errtab[66] ("floating point variable cannot occur in constant expression", 272);
  errtab[66] ("function reference cannot occur in constant expression", 274);
  errtab[66] ("instruction reference cannot occur in constant expression", 270);
  errtab[66] ("integer variable cannot occur in constant expression", 271);
  errtab[67] ("cannot mix floating point and integral in operands to binary right shift operator", 262);
  errtab[67] ("compile-time function call cannot occur in constant expression", 273);
  errtab[67] ("expected integral constant before ')' token", 41);
  errtab[67] ("floating point variable cannot occur in constant expression", 272);
  errtab[67] ("function reference cannot occur in constant expression", 274);
  errtab[67] ("instruction reference cannot occur in constant expression", 270);
  errtab[67] ("integer variable cannot occur in constant expression", 271);
  errtab[68] ("cannot mix floating point and integral in operands to binary addition operator", 262);
  errtab[68] ("compile-time function call cannot occur in constant expression", 273);
  errtab[68] ("expected integral constant before ')' token", 41);
  errtab[68] ("floating point variable cannot occur in constant expression", 272);
  errtab[68] ("function reference cannot occur in constant expression", 274);
  errtab[68] ("instruction reference cannot occur in constant expression", 270);
  errtab[68] ("integer variable cannot occur in constant expression", 271);
  errtab[69] ("cannot mix floating point and integral in operands to binary subtraction operator", 262);
  errtab[69] ("compile-time function call cannot occur in constant expression", 273);
  errtab[69] ("expected integral constant before ')' token", 41);
  errtab[69] ("floating point variable cannot occur in constant expression", 272);
  errtab[69] ("function reference cannot occur in constant expression", 274);
  errtab[69] ("instruction reference cannot occur in constant expression", 270);
  errtab[69] ("integer variable cannot occur in constant expression", 271);
  errtab[70] ("cannot mix floating point and integral in operands to binary multiplication operator", 262);
  errtab[70] ("compile-time function call cannot occur in constant expression", 273);
  errtab[70] ("expected integral constant before ')' token", 41);
  errtab[70] ("floating point variable cannot occur in constant expression", 272);
  errtab[70] ("function reference cannot occur in constant expression", 274);
  errtab[70] ("instruction reference cannot occur in constant expression", 270);
  errtab[70] ("integer variable cannot occur in constant expression", 271);
  errtab[71] ("cannot mix floating point and integral in operands to binary division operator", 262);
  errtab[71] ("compile-time function call cannot occur in constant expression", 273);
  errtab[71] ("expected integral constant before ')' token", 41);
  errtab[71] ("floating point variable cannot occur in constant expression", 272);
  errtab[71] ("function reference cannot occur in constant expression", 274);
  errtab[71] ("instruction reference cannot occur in constant expression", 270);
  errtab[71] ("integer variable cannot occur in constant expression", 271);
  errtab[72] ("cannot mix floating point and integral in operands to binary modulo division operator", 262);
  errtab[72] ("compile-time function call cannot occur in constant expression", 273);
  errtab[72] ("expected integral constant before ')' token", 41);
  errtab[72] ("floating point variable cannot occur in constant expression", 272);
  errtab[72] ("function reference cannot occur in constant expression", 274);
  errtab[72] ("instruction reference cannot occur in constant expression", 270);
  errtab[72] ("integer variable cannot occur in constant expression", 271);
  errtab[73] ("cannot mix floating point and integral in operands to binary power operator", 262);
  errtab[73] ("compile-time function call cannot occur in constant expression", 273);
  errtab[73] ("expected integral constant before ')' token", 41);
  errtab[73] ("floating point variable cannot occur in constant expression", 272);
  errtab[73] ("function reference cannot occur in constant expression", 274);
  errtab[73] ("instruction reference cannot occur in constant expression", 270);
  errtab[73] ("integer variable cannot occur in constant expression", 271);
  errtab[74] ("cannot mix floating point and integral in operands to binary addition operator", 261);
  errtab[74] ("expected floating point constant before ')' token", 41);
  errtab[75] ("cannot mix floating point and integral in operands to binary subtraction operator", 261);
  errtab[75] ("expected floating point constant before ')' token", 41);
  errtab[76] ("cannot mix floating point and integral in operands to binary multiplication operator", 261);
  errtab[76] ("expected floating point constant before ')' token", 41);
  errtab[77] ("cannot mix floating point and integral in operands to binary division operator", 261);
  errtab[77] ("expected floating point constant before ')' token", 41);
  errtab[78] ("cannot mix floating point and integral in operands to binary modulo division operator", 261);
  errtab[78] ("expected floating point constant before ')' token", 41);
  errtab[79] ("cannot mix floating point and integral in operands to binary power operator", 261);
  errtab[79] ("expected floating point constant before ')' token", 41);
